### ISSUE TITLE
SyntaxError exception when importing Notifications.jsx in an electron app.

### ISSUE THREAD

**Issue by W1M0R** [creativetimofficial/black-dashboard-react#3]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [✔️] I am running the latest version
- [✔️] I checked the documentation and found no answer
- [✔️] I checked to make sure that this issue has not already been filed
- [✔️] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Should not produce a SyntaxError exception in electron apps.

# Current Behavior

When using this theme in an electron app that uses the electron-react-boilerplate, the dashboard does not appear due to a syntax error exception being thrown.

# Failure Information (for bugs)

```
.\node_modules\react-notification-alert\dist\animate.css:7
.animated {
^

SyntaxError: Unexpected token .
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:660:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

See the related issue: https://github.com/creativetimofficial/react-notification-alert/issues/5

## Steps to Reproduce

1. Create an electron app using electron-react-boilerplate.
2. Modify your project to make use of this theme.
3. Run `yarn install` and then `yarn dev`.
4. Confirm that the above reported exception is thrown.
5. Edit the `routes.js` file and remove the `import Notifications from 'views/Notifications.jsx'` and the notifications entry in the routes array.
6. Confirm that the exception no longer appears and that the dashboard appears normally.

## Context

* Device: Desktop
* Operating System: Windows 10
* Browser and Version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

## Failure Logs

No log snippet available.

**Comment by W1M0R** [comment]
After upgrading `react-notification-alert` from `0.0.8` to `0.0.9` in my `package.json`, the problem was resolved.
